// ═══════════════════════════════════════
// VISUARIUM — DATA
// ═══════════════════════════════════════
// Para añadir una herramienta nueva, copia una entrada existente
// dentro de la categoría correcta y edita sus campos.
//
// Campos disponibles:
//   name       → Nombre de la herramienta (string)
//   url        → URL principal
//   visitUrl   → URL alternativa para el botón "Ver ganadores" (opcional)
//   price      → 'free' | 'freemium' | 'paid'
//   type       → { es: '...', en: '...' }  — etiqueta de tipo
//   desc       → { es: '...', en: '...' }  — descripción bilingüe
//   tags       → [ { es: '...', en: '...' }, ... ]
//   featured   → true  (opcional, muestra badge "Destacado")
//   isNew      → true  (opcional, muestra badge "New")
//   award      → { es: '...', en: '...' }  (opcional, solo categoría 'awarded')
// ═══════════════════════════════════════

const SUBCATEGORIES = [
  { id:'cinematography', name:{es:'Cinematografía & Spots',en:'Cinematography & Spots'}, tools:[
    { type:{es:'Biblioteca cinematográfica',en:'Cinematographic library'}, name:'ShotDeck', url:'https://shotdeck.com', price:'paid', desc:{es:'Millones de fotogramas buscables por color, composición, iluminación y emoción. Creado por el DOP nominado al Oscar Lawrence Sher.',en:'Millions of searchable frames by color, composition, lighting and mood. Created by Oscar-nominated DP Lawrence Sher.'}, tags:[{es:'Fotogramas',en:'Frames'},{es:'Color',en:'Color'},{es:'Iluminación',en:'Lighting'}], featured:true },
    { type:{es:'Galería cinematográfica',en:'Cinematographic gallery'}, name:'Film Grab', url:'https://film-grab.com', price:'free', desc:{es:'Capturas de películas por título. Cuando tienes un referente concreto en mente y quieres explorar su lenguaje visual completo.',en:'Film stills organized by title. Perfect when you have a specific film in mind and want to study its visual language.'}, tags:[{es:'Por película',en:'By film'},{es:'Fotogramas',en:'Frames'},{es:'Gratis',en:'Free'}] },
    { type:{es:'Análisis de color',en:'Color analysis'}, name:'Shot Cafe', url:'https://shot.cafe', price:'free', desc:{es:'Fotogramas con RGB Parade incluido. Para comunicar el tratamiento de color exacto a tu colorista sin ambigüedades.',en:'Film frames with built-in RGB Parade. The clearest way to communicate color grading intent to your colorist.'}, tags:[{es:'Etalonaje',en:'Color grading'},{es:'RGB Parade',en:'RGB Parade'},{es:'Color',en:'Color'}] },
    { type:{es:'IA + referencia',en:'AI + reference'}, name:'Film Vibes', url:'https://filmvibes.io', price:'free', desc:{es:'Describes el mood y te devuelve fotogramas de spots relevantes. Búsqueda semántica por IA orientada a publicidad audiovisual.',en:'Describe the mood and get relevant spot frames back. AI-powered semantic search for audiovisual advertising.'}, tags:[{es:'IA',en:'AI'},{es:'Spots',en:'Spots'},{es:'Mood',en:'Mood'}], isNew: true },
    { type:{es:'IA cinematográfica',en:'Cinematographic AI'}, name:'Flim', url:'https://app.flim.ai', price:'freemium', desc:{es:'Buscador de referencias cinematográficas con IA. Filtra por color, mood, composición y más en una base de datos masiva de fotogramas.',en:'AI-powered cinematographic reference search. Filter by color, mood, composition and more across a massive frame database.'}, tags:[{es:'IA',en:'AI'},{es:'Fotogramas',en:'Frames'},{es:'Búsqueda',en:'Search'}] },
    { type:{es:'Técnicas en movimiento',en:'Motion techniques'}, name:'Eyecandy', url:'https://eyecannndy.com', price:'free', desc:{es:'Técnicas cinematográficas en GIF: crash zoom, split diopter, match cut... Para comunicar con el director sin ambigüedades.',en:'Cinematic techniques as looping GIFs: crash zoom, split diopter, match cut and more. The fastest way to align with your director.'}, tags:[{es:'Técnicas',en:'Techniques'},{es:'GIFs',en:'GIFs'},{es:'Cámara',en:'Camera'}] },
    { type:{es:'Biblioteca mixta',en:'Mixed library'}, name:'Frame Set', url:'https://frameset.app', price:'freemium', desc:{es:'+430.000 fotogramas con filtros para comerciales. Para encontrar el tipo de plano exacto que necesitas.',en:'430K+ frames with filters for commercials. Find the exact shot type you need.'}, tags:[{es:'Planos',en:'Shots'},{es:'Comerciales',en:'Commercials'},{es:'+430k',en:'+430k'}] },
    { type:{es:'Fotogramas completos',en:'Complete frames'}, name:'Every Single Frame', url:'https://www.everysingleframe.com', price:'free', desc:{es:'Cada fotograma de películas icónicas mostrado como póster visual. Una forma única de ver el lenguaje de color y ritmo de una película entera.',en:'Every frame of iconic films displayed as a visual poster. A unique way to see the color language and rhythm of an entire film.'}, tags:[{es:'Fotogramas',en:'Frames'},{es:'Pósters',en:'Posters'},{es:'Color',en:'Color'}] },
    { type:{es:'Directorio de directores',en:'Directors directory'}, name:"Director's Library", url:'https://directorslibrary.com', price:'free', desc:{es:'Directorio de directores de cine publicitario con sus trabajos. Para buscar el director adecuado por estilo y reel.',en:'Directory of advertising film directors with their work. Find the right director by style and reel.'}, tags:[{es:'Directores',en:'Directors'},{es:'Spots',en:'Spots'},{es:'Reels',en:'Reels'}] },
    { type:{es:'Diálogos de cine',en:'Film dialogue'}, name:'PlayPhrase', url:'https://www.playphrase.me', price:'free', desc:{es:'Busca cualquier frase y encuentra el clip de película donde se dice. Para referencias de diálogo, tono y actuación.',en:'Type any phrase and find the exact movie clip where it\'s spoken. Great for dialogue, tone and performance references.'}, tags:[{es:'Diálogos',en:'Dialogue'},{es:'Clips',en:'Clips'},{es:'Búsqueda',en:'Search'}] },
  ]},

  { id:'graphic', name:{es:'Gráfica & Print',en:'Graphic & Print'}, tools:[
    { type:{es:'Gráfica publicitaria',en:'Advertising graphics'}, name:"Lürzer's Archive", url:'https://www.luerzersarchive.com', price:'freemium', desc:{es:'La biblia del diseño gráfico publicitario desde 1984. Print, poster, packaging.',en:'The bible of advertising graphic design since 1984. Print, poster, packaging.'}, tags:[{es:'Print',en:'Print'},{es:'Gráfica',en:'Graphics'},{es:'Histórico',en:'Historic'}], featured:true },
    { type:{es:'Portfolios creativos',en:'Creative portfolios'}, name:'Behance', url:'https://behance.net', price:'free', desc:{es:'Para buscar fotógrafos y directores por estilo. Cuando necesitas encontrar el talento adecuado para una estética muy definida.',en:'Browse photographers and directors by style. Ideal when you need specific talent for a well-defined visual aesthetic.'}, tags:[{es:'Fotógrafos',en:'Photographers'},{es:'Directores',en:'Directors'},{es:'Talento',en:'Talent'}] },
    { type:{es:'Diseño web curado',en:'Curated web design'}, name:'Siteinspire', url:'https://siteinspire.com', price:'free', desc:{es:'Galería curada de diseño web de alta calidad. Para referencias de composición y jerarquía tipográfica en piezas digitales.',en:'Curated gallery of high-quality web design. For composition and typographic hierarchy references in digital pieces.'}, tags:[{es:'Composición',en:'Composition'},{es:'Tipografía',en:'Typography'},{es:'Digital',en:'Digital'}] },
    { type:{es:'Pósters tipográficos',en:'Typographic posters'}, name:'Typographic Posters', url:'https://www.typographicposters.com', price:'free', desc:{es:'Galería curada de pósters tipográficos de todo el mundo. Referencia pura para diseño gráfico con tipografía como protagonista.',en:'Curated gallery of typographic posters from around the world. Pure reference for graphic design with typography as the star.'}, tags:[{es:'Pósters',en:'Posters'},{es:'Tipografía',en:'Typography'},{es:'Galería',en:'Gallery'}] },
    { type:{es:'Inspiración visual',en:'Visual inspiration'}, name:'Designspiration', url:'https://designspiration.com', price:'free', desc:{es:'Buscador visual que permite buscar por colores y composiciones. Ideal para explorar estilos gráficos y construir moodboards.',en:'Visual search engine that lets you search by colors and compositions. Ideal for exploring graphic styles and building moodboards.'}, tags:[{es:'Moodboards',en:'Moodboards'},{es:'Color',en:'Color'},{es:'Visual',en:'Visual'}] },
    { type:{es:'Pósters con causa',en:'Posters with a cause'}, name:'Poster for Tomorrow', url:'https://www.posterfortomorrow.org/en/gallery', price:'free', desc:{es:'Galería de pósters con mensaje social de diseñadores de todo el mundo. Creatividad aplicada a causas reales.',en:'Gallery of social message posters from designers worldwide. Creativity applied to real causes.'}, tags:[{es:'Social',en:'Social'},{es:'Pósters',en:'Posters'},{es:'Global',en:'Global'}] },
    { type:{es:'Diseño web brutalista',en:'Brutalist web design'}, name:'Brutalist Websites', url:'https://brutalistwebsites.com', price:'free', desc:{es:'Directorio de diseño web brutalista. Cuando necesitas referencias que rompan con lo convencional.',en:'Brutalist web design directory. When you need references that break from convention.'}, tags:[{es:'Brutalista',en:'Brutalist'},{es:'Web',en:'Web'},{es:'Experimental',en:'Experimental'}] },
    { type:{es:'Archivo de pósters',en:'Poster archive'}, name:'Poster Plakat', url:'https://www.posterplakat.com', price:'free', desc:{es:'Archivo histórico de pósters desde el Art Nouveau hasta el diseño contemporáneo. Historia visual del cartel.',en:'Historical poster archive from Art Nouveau to contemporary design. Visual history of the poster.'}, tags:[{es:'Archivo',en:'Archive'},{es:'Histórico',en:'Historic'},{es:'Pósters',en:'Posters'}] },
    { type:{es:'Mejor cartelismo',en:'Best poster design'}, name:'100 Beste Plakate', url:'https://100-beste-plakate.de', price:'free', desc:{es:'Los 100 mejores pósters del espacio de habla alemana, seleccionados anualmente. El estándar de excelencia en cartelismo.',en:'The 100 best posters from the German-speaking world, selected annually. The standard of excellence in poster design.'}, tags:[{es:'Concurso',en:'Competition'},{es:'Anual',en:'Annual'},{es:'Excelencia',en:'Excellence'}] },
    { type:{es:'Alianza gráfica',en:'Graphic alliance'}, name:'AGI', url:'https://a-g-i.org', price:'free', desc:{es:'Alliance Graphique Internationale. La élite global del diseño gráfico reunida en una organización. Miembros por invitación.',en:'Alliance Graphique Internationale. The global elite of graphic design in one organization. Invitation-only members.'}, tags:[{es:'Élite',en:'Elite'},{es:'Diseño',en:'Design'},{es:'Global',en:'Global'}] },
    { type:{es:'Competición de diseño',en:'Design competition'}, name:'Graphis Poster', url:'https://graphis.com/competitions/poster', price:'free', desc:{es:'Competición internacional de pósters de Graphis. Trabajo premiado de dirección de arte y diseño gráfico global.',en:'Graphis international poster competition. Award-winning art direction and global graphic design work.'}, tags:[{es:'Premios',en:'Awards'},{es:'Pósters',en:'Posters'},{es:'Diseño',en:'Design'}] },
    { type:{es:'Estudio de diseño',en:'Design studio'}, name:'Visuelle', url:'https://visuelle.co.uk', price:'free', desc:{es:'Portfolio y blog de diseño gráfico editorial y corporativo. Referencia de identidad visual y branding de alta calidad.',en:'Editorial and corporate graphic design portfolio and blog. High-quality visual identity and branding reference.'}, tags:[{es:'Branding',en:'Branding'},{es:'Editorial',en:'Editorial'},{es:'Identidad',en:'Identity'}] },
    { type:{es:'Diseño de portadas',en:'Cover design'}, name:'Cover Junkie', url:'https://coverjunkie.substack.com/archive', price:'free', desc:{es:'Archivo de las mejores portadas de revistas del mundo. Para referencias de diseño editorial, composición y tipografía en portada.',en:'Archive of the world\'s best magazine covers. For editorial design, composition and cover typography references.'}, tags:[{es:'Portadas',en:'Covers'},{es:'Editorial',en:'Editorial'},{es:'Revistas',en:'Magazines'}] },
  ]},

  { id:'art', name:{es:'Arte & Cultura',en:'Art & Culture'}, tools:[
    { type:{es:'Arte & cultura',en:'Art & culture'}, name:'Colossal', url:'https://thisiscolossal.com', price:'free', desc:{es:'Arte contemporáneo, fotografía e instalación. Para cuando la idea necesita salir del mundo publicitario y conectar con algo más grande.',en:'Contemporary art, photography and installation. For when the idea needs to go beyond advertising and connect with something bigger.'}, tags:[{es:'Arte',en:'Art'},{es:'Cultura',en:'Culture'},{es:'Instalación',en:'Installation'}] },
    { type:{es:'Industria creativa',en:'Creative industry'}, name:"It's Nice That", url:'https://itsnicethat.com', price:'free', desc:{es:'La referencia de la industria creativa global. Diseño, publicidad e ilustración con criterio editorial sólido.',en:'The reference for the global creative industry. Design, advertising and illustration with solid editorial criteria.'}, tags:[{es:'Diseño',en:'Design'},{es:'Publicidad',en:'Advertising'},{es:'Editorial',en:'Editorial'}] },
    { type:{es:'Creadores globales',en:'Global creators'}, name:'WePresent', url:'https://wepresent.wetransfer.com', price:'free', desc:{es:'Historias sobre artistas, fotógrafos y cineastas del mundo entero. Para cuando necesitas un referente humano, no solo visual.',en:'Stories about artists, photographers and filmmakers from around the world. When you need a human reference, not just visual.'}, tags:[{es:'Artistas',en:'Artists'},{es:'Historias',en:'Stories'},{es:'Global',en:'Global'}] },
    { type:{es:'Cultura visual',en:'Visual culture'}, name:'Nowness', url:'https://nowness.com', price:'free', desc:{es:'Cortometrajes, documentales y piezas de arte visual comisionadas. Cuando necesitas referencias que trascienden la publicidad.',en:'Short films, documentaries and commissioned visual art pieces. When you need references that transcend advertising.'}, tags:[{es:'Cortometrajes',en:'Short films'},{es:'Arte',en:'Art'},{es:'Premium',en:'Premium'}] },
  ]},

  { id:'stock', name:{es:'Stock Foto & Video',en:'Stock Photo & Video'}, tools:[
    { type:{es:'Fotografía gratuita',en:'Free photography'}, name:'Unsplash', url:'https://unsplash.com', price:'free', desc:{es:'La mejor biblioteca de fotos gratuitas en alta resolución. Licencia libre para uso comercial sin atribución.',en:'The best free high-resolution photo library. Free license for commercial use without attribution.'}, tags:[{es:'Fotos',en:'Photos'},{es:'Gratis',en:'Free'},{es:'Alta resolución',en:'High-res'}], featured:true },
    { type:{es:'Fotos y video',en:'Photos & video'}, name:'Pexels', url:'https://pexels.com', price:'free', desc:{es:'Fotos y videos gratuitos. Alternativa a Unsplash con buena selección de video stock.',en:'Free photos and videos. Alternative to Unsplash with good video stock selection.'}, tags:[{es:'Fotos',en:'Photos'},{es:'Video',en:'Video'},{es:'Gratis',en:'Free'}] },
    { type:{es:'Video cinematográfico',en:'Cinematic video'}, name:'Artgrid', url:'https://artgrid.io', price:'paid', desc:{es:'Stock de video cinematográfico premium. De los creadores de Artlist, calidad de producción profesional.',en:'Premium cinematic video stock. From Artlist creators, professional production quality.'}, tags:[{es:'Video',en:'Video'},{es:'Cinematográfico',en:'Cinematic'},{es:'Premium',en:'Premium'}], featured:true },
    { type:{es:'Video gratuito',en:'Free video'}, name:'Pexels Video', url:'https://pexels.com/videos', price:'free', desc:{es:'Videos gratuitos para proyectos con presupuesto limitado.',en:'Free stock videos for projects with tight budgets.'}, tags:[{es:'Video',en:'Video'},{es:'Gratis',en:'Free'},{es:'Stock',en:'Stock'}] },
    { type:{es:'Video para web',en:'Web video'}, name:'Coverr', url:'https://coverr.co', price:'free', desc:{es:'Videos gratuitos pensados para fondos web y headers. Loops y clips cortos de alta calidad.',en:'Free videos designed for web backgrounds and headers. High-quality loops and short clips.'}, tags:[{es:'Web',en:'Web'},{es:'Loops',en:'Loops'},{es:'Gratis',en:'Free'}] },
  ]},

  { id:'typography', name:{es:'Tipografía',en:'Typography'}, tools:[
    { type:{es:'Tipografía en contexto',en:'Typography in context'}, name:'Fonts In Use', url:'https://fontsinuse.com', price:'free', desc:{es:'Tipografía en contexto real. Para ver cómo se usan las fuentes en proyectos reales de diseño, editorial y publicidad.',en:'Typography in real context. See how fonts are used in actual design, editorial and advertising projects.'}, tags:[{es:'Tipografía',en:'Typography'},{es:'Contexto',en:'Context'},{es:'Editorial',en:'Editorial'}], featured:true },
    { type:{es:'Combinaciones tipográficas',en:'Font pairings'}, name:'Typewolf', url:'https://typewolf.com', price:'free', desc:{es:'Combinaciones tipográficas y tendencias. Recomendaciones de fuentes similares y pairings que funcionan.',en:'Font pairings and trends. Similar font recommendations and pairings that work.'}, tags:[{es:'Pairings',en:'Pairings'},{es:'Tendencias',en:'Trends'},{es:'Recomendaciones',en:'Recommendations'}] },
    { type:{es:'Google Fonts',en:'Google Fonts'}, name:'FontPair', url:'https://fontpair.co', price:'free', desc:{es:'Combinaciones de Google Fonts que funcionan juntas. Para proyectos con presupuesto limitado de tipografía.',en:'Google Fonts combinations that work together. For projects with limited typography budget.'}, tags:[{es:'Google Fonts',en:'Google Fonts'},{es:'Pairings',en:'Pairings'},{es:'Gratis',en:'Free'}] },
    { type:{es:'Escala tipográfica',en:'Type scale'}, name:'Type Scale', url:'https://typescale.com', price:'free', desc:{es:'Generador de escalas tipográficas. Para establecer jerarquía visual consistente en cualquier proyecto.',en:'Type scale generator. Establish consistent visual hierarchy in any project.'}, tags:[{es:'Escala',en:'Scale'},{es:'Jerarquía',en:'Hierarchy'},{es:'Herramienta',en:'Tool'}] },
    { type:{es:'Fundición tipográfica',en:'Type foundry'}, name:'Pangram Pangram', url:'https://pangrampangram.com', price:'freemium', desc:{es:'Fundición tipográfica independiente con fuentes de alta calidad. Trial fonts gratuitas para explorar.',en:'Independent type foundry with high-quality fonts. Free trial fonts to explore.'}, tags:[{es:'Fundición',en:'Foundry'},{es:'Fuentes',en:'Fonts'},{es:'Trial',en:'Trial'}] },
    { type:{es:'Tipografía chilena',en:'Chilean typography'}, name:'Quintana', url:'https://quintana-font.cl', price:'free', desc:{es:'Proyecto tipográfico chileno de código abierto. Fuentes diseñadas con identidad latinoamericana.',en:'Chilean open-source typography project. Fonts designed with Latin American identity.'}, tags:[{es:'Open source',en:'Open source'},{es:'LATAM',en:'LATAM'},{es:'Display',en:'Display'}] },
    { type:{es:'Tipografía open source',en:'Open source typography'}, name:'The League of Moveable Type', url:'https://www.theleagueofmoveabletype.com', price:'free', desc:{es:'La primera fundición tipográfica open source. Fuentes gratuitas de alta calidad con licencia abierta.',en:'The first open-source type foundry. High-quality free fonts with open license.'}, tags:[{es:'Open source',en:'Open source'},{es:'Gratis',en:'Free'},{es:'Fundición',en:'Foundry'}] },
  ]},

  { id:'color', name:{es:'Color',en:'Color'}, tools:[
    { type:{es:'Generador de paletas',en:'Palette generator'}, name:'Coolors', url:'https://coolors.co', price:'freemium', desc:{es:'Generador de paletas de color. Genera, explora y guarda combinaciones de colores para cualquier proyecto.',en:'Color palette generator. Generate, explore and save color combinations for any project.'}, tags:[{es:'Paletas',en:'Palettes'},{es:'Generador',en:'Generator'},{es:'Exportar',en:'Export'}], featured:true },
    { type:{es:'Paletas con IA',en:'AI palettes'}, name:'Khroma', url:'https://khroma.co', price:'free', desc:{es:'Generador de paletas con IA. Aprende tus preferencias y genera paletas personalizadas infinitas.',en:'AI-powered palette generator. Learns your preferences and generates infinite personalized palettes.'}, tags:[{es:'IA',en:'AI'},{es:'Personalizado',en:'Personalized'},{es:'Paletas',en:'Palettes'}] },
    { type:{es:'Paletas curadas',en:'Curated palettes'}, name:'Color Hunt', url:'https://colorhunt.co', price:'free', desc:{es:'Paletas de color curadas por la comunidad. Miles de combinaciones organizadas por popularidad y tendencia.',en:'Community-curated color palettes. Thousands of combinations organized by popularity and trend.'}, tags:[{es:'Comunidad',en:'Community'},{es:'Tendencias',en:'Trends'},{es:'Curado',en:'Curated'}] },
    { type:{es:'Rueda de color',en:'Color wheel'}, name:'Adobe Color', url:'https://color.adobe.com', price:'free', desc:{es:'Rueda de color y extracción de paletas desde imágenes. Integración directa con Creative Cloud.',en:'Color wheel and palette extraction from images. Direct Creative Cloud integration.'}, tags:[{es:'Adobe',en:'Adobe'},{es:'Extracción',en:'Extraction'},{es:'Rueda de color',en:'Color wheel'}] },
    { type:{es:'Paletas generativas',en:'Generative palettes'}, name:'Genery', url:'https://genery.io', price:'free', desc:{es:'Generador de paletas de color con enfoque creativo. Explora combinaciones inesperadas para tus proyectos.',en:'Color palette generator with creative focus. Explore unexpected combinations for your projects.'}, tags:[{es:'Generador',en:'Generator'},{es:'Paletas',en:'Palettes'},{es:'Creativo',en:'Creative'}] },
  ]},

  { id:'music', name:{es:'Música & Sonido',en:'Music & Sound'}, tools:[
    { type:{es:'Música para publicidad',en:'Music for advertising'}, name:'Epidemic Sound', url:'https://epidemicsound.com', price:'paid', desc:{es:'Biblioteca de música y efectos para publicidad. Licencia clara para uso comercial en spots y contenido de marca.',en:'Music and sound effects library for advertising. Clear license for commercial use in spots and branded content.'}, tags:[{es:'Licencia comercial',en:'Commercial license'},{es:'Spots',en:'Spots'},{es:'SFX',en:'SFX'}], featured:true },
    { type:{es:'Música premium',en:'Premium music'}, name:'Artlist', url:'https://artlist.io', price:'paid', desc:{es:'Música y efectos de sonido premium. Licencia universal para cualquier uso comercial con suscripción.',en:'Premium music and sound effects. Universal license for any commercial use with subscription.'}, tags:[{es:'Premium',en:'Premium'},{es:'Licencia universal',en:'Universal license'},{es:'Música',en:'Music'}] },
    { type:{es:'Música de artistas',en:'Artist music'}, name:'Musicbed', url:'https://musicbed.com', price:'paid', desc:{es:'Música de artistas reales para publicidad. Cuando necesitas una canción con alma, no solo un tema de librería.',en:'Music by real artists, made for advertising. For when you need a track with genuine emotion, not just background noise.'}, tags:[{es:'Artistas reales',en:'Real artists'},{es:'Premium',en:'Premium'},{es:'Spots',en:'Spots'}] },
    { type:{es:'Música gratuita',en:'Free music'}, name:'Free Music Archive', url:'https://freemusicarchive.org', price:'free', desc:{es:'Archivo de música gratuita con licencias Creative Commons. Para proyectos con presupuesto cero.',en:'Free music archive with Creative Commons licenses. For projects with zero budget.'}, tags:[{es:'Creative Commons',en:'Creative Commons'},{es:'Gratis',en:'Free'},{es:'Archivo',en:'Archive'}] },
    { type:{es:'Efectos de sonido',en:'Sound effects'}, name:'Freesound', url:'https://freesound.org', price:'free', desc:{es:'Base de datos colaborativa de sonidos con licencias Creative Commons. Desde ambientes hasta efectos específicos.',en:'Collaborative sound database with Creative Commons licenses. From ambiences to specific effects.'}, tags:[{es:'SFX',en:'SFX'},{es:'Creative Commons',en:'Creative Commons'},{es:'Colaborativo',en:'Collaborative'}] },
    { type:{es:'Archivo sonoro BBC',en:'BBC sound archive'}, name:'BBC Sound Effects', url:'https://sound-effects.bbcrewind.co.uk', price:'free', desc:{es:'Archivo de efectos de sonido de la BBC. Miles de grabaciones profesionales de campo, ambientes y efectos.',en:'BBC sound effects archive. Thousands of professional field recordings, ambiences and effects.'}, tags:[{es:'BBC',en:'BBC'},{es:'Profesional',en:'Professional'},{es:'Archivo',en:'Archive'}] },
    { type:{es:'Efectos gratuitos',en:'Free effects'}, name:'ZapSplat', url:'https://zapsplat.com', price:'free', desc:{es:'Biblioteca de efectos de sonido y música gratuitos. Más de 130.000 sonidos organizados por categoría.',en:'Free sound effects and music library. Over 130,000 sounds organized by category.'}, tags:[{es:'130k+ sonidos',en:'130k+ sounds'},{es:'Gratis',en:'Free'},{es:'Categorizado',en:'Categorized'}] },
  ]},

  { id:'motion', name:{es:'Ilustración & Motion',en:'Illustration & Motion'}, tools:[
    { type:{es:'Portfolios creativos',en:'Creative portfolios'}, name:'Dribbble', url:'https://dribbble.com', price:'free', desc:{es:'Portfolios de ilustradores, animadores y diseñadores. Para encontrar talento por estilo visual específico.',en:'Portfolios of illustrators, animators and designers. Find talent by specific visual style.'}, tags:[{es:'Portfolios',en:'Portfolios'},{es:'Talento',en:'Talent'},{es:'Ilustración',en:'Illustration'}], featured:true },
    { type:{es:'Títulos de cine',en:'Film titles'}, name:'Art of the Title', url:'https://artofthetitle.com', price:'free', desc:{es:'Archivo de secuencias de títulos de cine y TV. Motion graphics y diseño de títulos analizados en detalle.',en:'Archive of film and TV title sequences. Motion graphics and title design analyzed in detail.'}, tags:[{es:'Títulos',en:'Titles'},{es:'Motion',en:'Motion'},{es:'Análisis',en:'Analysis'}] },
    { type:{es:'Motion graphics',en:'Motion graphics'}, name:'Stash Media', url:'https://stashmedia.tv', price:'freemium', desc:{es:'Archivo de motion graphics, animación y spots. Para referencias de animación publicitaria y técnicas visuales.',en:'Motion graphics, animation and spots archive. For advertising animation references and visual techniques.'}, tags:[{es:'Motion graphics',en:'Motion graphics'},{es:'Animación',en:'Animation'},{es:'Spots',en:'Spots'}] },
    { type:{es:'End cards',en:'End cards'}, name:'Art of End Cards', url:'https://theartofendcards.com', price:'free', desc:{es:'La única referencia especializada en end cards de spots. Para resolver cómo conviven logo, claim, pack shot y legal.',en:'The only specialized end card reference. To figure out how logo, claim, pack shot and legal coexist.'}, tags:[{es:'End cards',en:'End cards'},{es:'TV',en:'TV'},{es:'Logo',en:'Logo'}] },
    { type:{es:'Motion graphics curado',en:'Curated motion graphics'}, name:'Motionographer', url:'https://motionographer.com', price:'free', desc:{es:'La referencia global de motion graphics y animación. Proyectos curados de estudios y artistas de motion de todo el mundo.',en:'The global reference for motion graphics and animation. Curated projects from motion studios and artists worldwide.'}, tags:[{es:'Motion',en:'Motion'},{es:'Animación',en:'Animation'},{es:'Curado',en:'Curated'}], featured:true },
    { type:{es:'Experimentos web',en:'Web experiments'}, name:'Codrops', url:'https://tympanus.net/codrops', price:'free', desc:{es:'Experimentos de animación web, efectos y transitions. Para referencias de microinteracciones y motion en interfaces.',en:'Web animation experiments, effects and transitions. For microinteraction and interface motion references.'}, tags:[{es:'Web',en:'Web'},{es:'Experimentos',en:'Experiments'},{es:'Código',en:'Code'}] },
    { type:{es:'Animación independiente',en:'Independent animation'}, name:'Cartoon Brew', url:'https://cartoonbrew.com', price:'free', desc:{es:'Noticias y showcase de animación independiente. Desde cortos experimentales hasta técnicas de animación innovadoras.',en:'Independent animation news and showcase. From experimental shorts to innovative animation techniques.'}, tags:[{es:'Animación',en:'Animation'},{es:'Independiente',en:'Independent'},{es:'Técnicas',en:'Techniques'}] },
    { type:{es:'Arte & diseño curado',en:'Curated art & design'}, name:'Booooooom', url:'https://www.booooooom.com', price:'free', desc:{es:'Comunidad de arte contemporáneo, ilustración y motion. Contenido curado diariamente desde 2008.',en:'Contemporary art, illustration and motion community. Daily curated content since 2008.'}, tags:[{es:'Arte',en:'Art'},{es:'Ilustración',en:'Illustration'},{es:'Comunidad',en:'Community'}] },
    { type:{es:'Premios de motion',en:'Motion awards'}, name:'Motion Design Awards', url:'https://motiondesignawards.com', price:'free', desc:{es:'Premios anuales de motion design con galería de ganadores. Lo mejor del motion graphics, animación y diseño en movimiento.',en:'Annual motion design awards with winner gallery. The best of motion graphics, animation and motion design.'}, tags:[{es:'Premios',en:'Awards'},{es:'Motion',en:'Motion'},{es:'Ganadores',en:'Winners'}] },
  ]},

  { id:'campaigns', name:{es:'Archivo de campañas',en:'Campaign Archive'}, tools:[
    { type:{es:'Campañas diarias',en:'Daily campaigns'}, name:'The Drum Creative Works', url:'https://thedrum.com/creative-works', price:'free', desc:{es:'Campañas nuevas de todo el mundo actualizadas cada día. El pulso en tiempo real de lo que se está produciendo.',en:'New campaigns from around the world updated daily. The real-time pulse of what\'s being produced.'}, tags:[{es:'Actualidad',en:'Current'},{es:'Diario',en:'Daily'},{es:'Global',en:'Global'}], featured:true },
    { type:{es:'Archivo de campañas',en:'Campaign archive'}, name:'Ads of the World', url:'https://adsoftheworld.com', price:'free', desc:{es:'La mayor base de datos de campañas globales. Filtra por sector, país y medio.',en:'The largest global campaign archive. Filter by industry, country and medium to find exactly what you need.'}, tags:[{es:'Campañas',en:'Campaigns'},{es:'Por sector',en:'By industry'},{es:'Global',en:'Global'}] },
    { type:{es:'Directorio de agencias',en:'Agency directory'}, name:'AdForum', url:'https://adforum.com', price:'free', desc:{es:'Agencias, productoras y campañas filtradas por premios.',en:'Agencies, production companies and campaigns filtered by awards.'}, tags:[{es:'Agencias',en:'Agencies'},{es:'Premios',en:'Awards'},{es:'Historia',en:'History'}] },
    { type:{es:'Casos creativos',en:'Creative cases'}, name:'Campaigns of the World', url:'https://campaignsoftheworld.com', price:'free', desc:{es:'Campañas con contexto estratégico. Entiende por qué se tomaron las decisiones visuales y de copy.',en:'Campaigns presented with strategic context. Understand the thinking behind every visual and copy decision.'}, tags:[{es:'Estrategia',en:'Strategy'},{es:'Contexto',en:'Context'},{es:'Global',en:'Global'}] },
    { type:{es:'Archivo histórico',en:'Historical archive'}, name:'Vintage Ad Browser', url:'https://vintageadbrowser.com', price:'free', desc:{es:'Publicidad clásica pre-digital. Para entender los orígenes visuales y de copy de una marca.',en:'Classic pre-digital advertising. To understand the visual and copy origins of a brand.'}, tags:[{es:'Vintage',en:'Vintage'},{es:'Histórico',en:'Historic'},{es:'Marcas',en:'Brands'}] },
    { type:{es:'Desbloqueo creativo',en:'Creative unblock'}, name:'Unblock Coffee', url:'https://www.unblock.coffee', price:'free', desc:{es:'Herramienta de desbloqueo creativo con prompts visuales aleatorios. Para cuando necesitas un empujón inesperado.',en:'Creative unblock tool with random visual prompts. For when you need an unexpected push.'}, tags:[{es:'Desbloqueo',en:'Unblock'},{es:'Prompts',en:'Prompts'},{es:'Aleatorio',en:'Random'}] },
  ]},

  { id:'awarded', name:{es:'Trabajo premiado',en:'Award-winning Work'}, tools:[
    { type:{es:'Archivo Cannes',en:'Cannes archive'}, name:'Love The Work More', url:'https://lovetheworkmore.com', visitUrl:'https://lovetheworkmore.com', price:'free', desc:{es:'Todos los Grand Prix de Cannes Lions desde 1954 hasta hoy. La memoria más completa de la publicidad premiada.',en:'Every Cannes Lions Grand Prix from 1954 to today. The most complete memory of award-winning advertising.'}, tags:[{es:'Archivo',en:'Archive'},{es:'1954–hoy',en:'1954–today'},{es:'Gratis',en:'Free'}], award:{es:'Grand Prix desde 1954',en:'Grand Prix since 1954'}, featured:true },
    { type:{es:'El festival',en:'The festival'}, name:'Cannes Lions', url:'https://canneslions.com', visitUrl:'https://canneslions.com/awards', price:'free', desc:{es:'El festival más importante del mundo desde 1954. El benchmark global de la creatividad en todas las disciplinas.',en:'The world\'s most important festival since 1954. The global creativity benchmark across all disciplines.'}, tags:[{es:'Cannes, Junio',en:'Cannes, June'},{es:'Global',en:'Global'},{es:'Todas las disciplinas',en:'All disciplines'}], award:{es:"Grand Prix · Titanium · Lion d'Or",en:"Grand Prix · Titanium · Lion d'Or"}, featured:true },
    { type:{es:'Diseño & dirección de arte',en:'Design & art direction'}, name:'D&AD', url:'https://dandad.org', visitUrl:'https://dandad.org/work/annual', price:'free', desc:{es:'El benchmark del diseño y la publicidad desde 1962. Ganar un Black Pencil es el máximo reconocimiento creativo.',en:'The design and advertising benchmark since 1962. Winning a Black Pencil is the ultimate creative recognition.'}, tags:[{es:'Londres',en:'London'},{es:'Diseño',en:'Design'},{es:'Film',en:'Film'},{es:'Copy',en:'Copy'}], award:{es:'Black Pencil · Yellow Pencil · Wood Pencil',en:'Black Pencil · Yellow Pencil · Wood Pencil'} },
    { type:{es:'Publicidad integral',en:'Integrated advertising'}, name:'Clio Awards', url:'https://clios.com', visitUrl:'https://clios.com/awards/winners', price:'free', desc:{es:'Fundados en 1959, uno de los premios más veteranos. Excelencia en publicidad, diseño y entretenimiento.',en:'Founded in 1959, one of the most veteran awards. Excellence in advertising, design and entertainment.'}, tags:[{es:'Nueva York',en:'New York'},{es:'Global',en:'Global'},{es:'Publicidad integral',en:'Integrated advertising'}], award:{es:'Grand Clio · Gold · Silver · Bronze',en:'Grand Clio · Gold · Silver · Bronze'} },
    { type:{es:'Craft & copywriting',en:'Craft & copywriting'}, name:'The One Show', url:'https://www.oneclub.org', visitUrl:'https://www.oneclub.org/the-one-show/', price:'free', desc:{es:'El festival del One Club. Idea y ejecución inseparables. Muy valorado en copywriting y craft cinematográfico.',en:'The One Club festival. Idea and execution inseparable. Highly valued in copywriting and cinematographic craft.'}, tags:[{es:'Nueva York',en:'New York'},{es:'Craft',en:'Craft'},{es:'Copy',en:'Copy'}], award:{es:'Gold Pencil · Best of Show',en:'Gold Pencil · Best of Show'} },
    { type:{es:'Festival iberoamericano',en:'Ibero-American festival'}, name:'El Sol', url:'https://elsolfestival.com', visitUrl:'https://elsolfestival.com/edic-anteriores/palmares/', price:'free', desc:{es:'Referencia iberoamericana desde 1986, celebrado en Málaga. 40 ediciones de lo mejor de España y LATAM.',en:'Ibero-American reference since 1986, held in Malaga. 40 editions of the best from Spain and LATAM.'}, tags:[{es:'Málaga, Mayo',en:'Malaga, May'},{es:'España + LATAM',en:'Spain + LATAM'},{es:'40 ediciones',en:'40 editions'}], award:{es:'Sol de Platino · Gran Premio · Sol de Oro',en:'Sol de Platino · Gran Premio · Sol de Oro'} },
    { type:{es:'Premios nacionales',en:'National awards'}, name:'C de C', url:'https://www.clubdecreatividad.com', visitUrl:'https://www.clubdecreatividad.com', price:'free', desc:{es:'Premios Nacionales de Creatividad del Club de Creativos. La radiografía más honesta de la creatividad española.',en:'National Creativity Awards from the Club de Creativos. The most honest X-ray of Spanish creativity.'}, tags:[{es:'San Sebastián, Marzo',en:'San Sebastián, March'},{es:'España',en:'Spain'},{es:'Todas las disciplinas',en:'All disciplines'}], award:{es:'Gran Premio · Oro · Plata · Bronce',en:'Grand Prize · Gold · Silver · Bronze'} },
    { type:{es:'Arte dirección & diseño',en:'Art direction & design'}, name:'ADC Annual Awards', url:'https://adcglobal.org', visitUrl:'https://adcglobal.org', price:'free', desc:{es:'Los premios del Art Directors Club, fundados en 1921. El reconocimiento más antiguo del diseño gráfico.',en:'The Art Directors Club awards, founded in 1921. The oldest recognition in graphic design.'}, tags:[{es:'Nueva York',en:'New York'},{es:'Dirección de arte',en:'Art direction'},{es:'Diseño gráfico',en:'Graphic design'}], award:{es:'Black Cube · Gold Cube · Silver Cube',en:'Black Cube · Gold Cube · Silver Cube'} },
  ]},

  { id:'experimental', name:{es:'Experimental & Fun',en:'Experimental & Fun'}, tools:[
    { type:{es:'Colección experimental',en:'Experimental collection'}, name:'Tooooools', url:'https://www.tooooools.app/', price:'free', desc:{es:'Colección de herramientas experimentales y generativas. Desde distorsión de imágenes hasta generadores de patrones únicos.',en:'Collection of experimental and generative tools. From image distortion to unique pattern generators.'}, tags:[{es:'Generativo',en:'Generative'},{es:'Experimental',en:'Experimental'},{es:'Colección',en:'Collection'}], featured:true },
    { type:{es:'Dibujo wiggly',en:'Wiggly drawing'}, name:'WigglyPaint', url:'https://internet-janitor.itch.io/wigglypaint', price:'free', desc:{es:'Herramienta de dibujo con efectos temblorosos y orgánicos. Para bocetos con personalidad y estética única.',en:'Drawing tool with wiggly and organic effects. For sketches with personality and unique aesthetics.'}, tags:[{es:'Dibujo',en:'Drawing'},{es:'Wiggly',en:'Wiggly'},{es:'Orgánico',en:'Organic'}], isNew:true },
    { type:{es:'Proyectos interactivos',en:'Interactive projects'}, name:'Neal.fun', url:'https://neal.fun', price:'free', desc:{es:'Colección de experimentos interactivos creativos. Desde visualizar el espacio profundo hasta simular gastos de millonarios.',en:'Collection of creative interactive experiments. From visualizing deep space to simulating billionaire spending.'}, tags:[{es:'Interactivo',en:'Interactive'},{es:'Experimentos',en:'Experiments'},{es:'Diversión',en:'Fun'}], featured:true },
    { type:{es:'Arte generativo',en:'Generative art'}, name:'Weavesilk', url:'http://weavesilk.com', price:'free', desc:{es:'Generador de arte simétrico interactivo. Dibuja y crea patrones hipnóticos con simetría radial.',en:'Interactive symmetric art generator. Draw and create hypnotic patterns with radial symmetry.'}, tags:[{es:'Arte',en:'Art'},{es:'Simetría',en:'Symmetry'},{es:'Generativo',en:'Generative'}] },
    { type:{es:'Música interactiva',en:'Interactive music'}, name:'Patatap', url:'https://patatap.com', price:'free', desc:{es:'Animaciones y sonidos portables. Cada tecla genera una animación y sonido único.',en:'Portable animations and sounds. Each key generates a unique animation and sound.'}, tags:[{es:'Música',en:'Music'},{es:'Animación',en:'Animation'},{es:'Interactivo',en:'Interactive'}] },
    { type:{es:'Opera con IA',en:'AI opera'}, name:'Blob Opera', url:'https://artsandculture.google.com/experiment/blob-opera/AAHWrq360NcGbw', price:'free', desc:{es:'Crea música operística arrastrando blobs. Machine Learning de Google Arts & Culture.',en:'Create operatic music by dragging blobs. Google Arts & Culture Machine Learning.'}, tags:[{es:'IA',en:'AI'},{es:'Música',en:'Music'},{es:'Google',en:'Google'}] },
    { type:{es:'Lab musical',en:'Music lab'}, name:'Chrome Music Lab', url:'https://musiclab.chromeexperements.com', price:'free', desc:{es:'Experimentos musicales interactivos de Chrome. Para entender y crear música de forma visual.',en:'Chrome interactive music experiments. To understand and create music visually.'}, tags:[{es:'Música',en:'Music'},{es:'Educativo',en:'Educational'},{es:'Chrome',en:'Chrome'}] },
    { type:{es:'Dibujo con IA',en:'AI drawing'}, name:'AutoDraw', url:'https://autodraw.com', price:'free', desc:{es:'Dibuja y la IA de Google adivina y mejora tu boceto. Para prototipos rápidos con ilustraciones reconocibles.',en:'Draw and Google AI guesses and improves your sketch. For quick prototypes with recognizable illustrations.'}, tags:[{es:'IA',en:'AI'},{es:'Dibujo',en:'Drawing'},{es:'Google',en:'Google'}] },
    { type:{es:'Radio mundial',en:'World radio'}, name:'Radio Garden', url:'http://radio.garden', price:'free', desc:{es:'Explora emisoras de radio de todo el mundo en un globo 3D interactivo. Para referencias de audio y cultura global.',en:'Explore radio stations worldwide on an interactive 3D globe. For audio references and global culture.'}, tags:[{es:'Radio',en:'Radio'},{es:'Global',en:'Global'},{es:'3D',en:'3D'}] },
    { type:{es:'Ventanas del mundo',en:'Windows to the world'}, name:'Window Swap', url:'https://window-swap.com', price:'free', desc:{es:'Mira por las ventanas de personas reales de todo el mundo. Referencias de luz natural, ambiente y locaciones auténticas.',en:'Look through real people\'s windows worldwide. Natural light, atmosphere and authentic location references.'}, tags:[{es:'Ventanas',en:'Windows'},{es:'Ambiente',en:'Atmosphere'},{es:'Luz natural',en:'Natural light'}] },
    { type:{es:'Escritura musical',en:'Musical typing'}, name:'Typatone', url:'https://typatone.com', price:'free', desc:{es:'Cada letra que escribes genera una nota musical. Escritura como composición sonora.',en:'Every letter you type generates a musical note. Writing as sound composition.'}, tags:[{es:'Música',en:'Music'},{es:'Tipeo',en:'Typing'},{es:'Generativo',en:'Generative'}] },
    { type:{es:'Ruido ambiental',en:'Ambient noise'}, name:'myNoise', url:'https://mynoise.net', price:'freemium', desc:{es:'Generador de ruido ambiental ultra-personalizable. Desde lluvia hasta cafeterías, con ecualizador paramétrico.',en:'Ultra-customizable ambient noise generator. Rain, coffee shops, forests — shaped with a parametric equalizer.'}, tags:[{es:'Ambiente',en:'Ambient'},{es:'Sonido',en:'Sound'},{es:'Concentración',en:'Focus'}] },
    { type:{es:'Dibujo colaborativo',en:'Collaborative drawing'}, name:'Magma', url:'https://magma.com', price:'free', desc:{es:'Pizarra de dibujo colaborativa en tiempo real. Para brainstorming visual remoto con múltiples cursores simultáneos.',en:'Real-time collaborative drawing board. For remote visual brainstorming with multiple simultaneous cursors.'}, tags:[{es:'Colaborativo',en:'Collaborative'},{es:'Dibujo',en:'Drawing'},{es:'Tiempo real',en:'Real-time'}] },
    { type:{es:'Glitch art',en:'Glitch art'}, name:'Photomosh', url:'https://photomosh.com', price:'free', desc:{es:'Efectos glitch en imágenes en tiempo real con más de 27 modos. Para estéticas distorsionadas, VHS y datamosh.',en:'Real-time glitch effects on images with 27+ modes. For distorted, VHS and datamosh aesthetics.'}, tags:[{es:'Glitch',en:'Glitch'},{es:'Efectos',en:'Effects'},{es:'VHS',en:'VHS'}] },
    { type:{es:'Música colaborativa',en:'Collaborative music'}, name:'Plink', url:'https://labs.dinahmoe.com/plink', price:'free', desc:{es:'Instrumento musical colaborativo online. Toca notas con otros usuarios en tiempo real.',en:'Online collaborative musical instrument. Play notes with other users in real-time.'}, tags:[{es:'Música',en:'Music'},{es:'Colaborativo',en:'Collaborative'},{es:'Tiempo real',en:'Real-time'}] },
  ]},
];
